name: Node CI

on:
  push:
    branches:
      - 'master'
jobs:
  update:
    if: github.ref == 'refs/heads/master'

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 18
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    - name: npm generate
      run: |
        npm install
        node src/merge.js

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./
        cname: fuzzy.raidenshogun.net
        user_name: 'nanashi'
        user_email: 'example@example.com'
        enable_jekyll: true
